language: python
branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+$

before_install:
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"
install:
  - pip3 install .
  - python3 -m pip install --upgrade build
  - pip3 install pytest

jobs:
  include:
    - name: "Run tests and create new version"
      if: branch = main
      python:
        - '3.8'
        - '3.9'
      script:
        - python3 -m pytest
      before_deploy:
        - CURRENT_VERSION=$(git describe --tags --abbrev=0)
        - >
          (git log $CURRENT_VERSION..HEAD | grep -q "\[bump:major\]" && BUMP=major) ||
          (git log $CURRENT_VERSION..HEAD | grep -q "\[bump:minor\]" && BUMP=minor) ||
          BUMP=patch
        - pip3 install bump2version
        - bump2version --curent-version="$CURRENT_VERSION" $BUMP --tag --no-configured-files
      deploy:
        provider: releases
        api_key:
          secure: "cHyeUGWIT1uP7oURUbl6hmiLmqc6KcJJxclE9K3EeFCE9Oe+tFDUIyz+nP0mqOFxwHJ7yETk0L/WTO1+Q9o3K/hXFxGaEKEkAtp0io86KVytxdE5nQ2EfRxFfz3HokrH+mEkEpLhtKvbrqJ1yqeleyRMuzzrkq7OIev3H//SZePz/PSSF/NnXnIxrzMDXQ+Mql+NR+BKLgqQHCzS0dzTI65fFiqUK1QStJkBcuKR6w3LMJsn4oH+bablro0cdCMPwcPVXifQHGXjo4khJJ7reWRjMfxA+QLDSLK5YfBUjq1/ZvfZBVOCDtEhKCGshv658pBstGkD9UCI+3WuhmM+lQfaLbrXILqhvnTz9eDmrYjjlWXIn86s1cE7+KJkqnvP6klcm4APRwGOwUoSZ3J6ITjTB3aid1IF1kFZyo/P5MUYl1j+kWEslmQpagdPlhMJhEXJB7VstRfSV0wDcUVrIEIAtA9IXiN/zQece6VNZzKAracJY+kyk9TJabs8LTgzH45j7gHpQgM3R1ewrbGb7oU/SnQxUlBSCx8p8XK1tAbL5RnboNZIJZfK8CCGaN45KeVzje4L+zU8BanR/xofYmiEA8T8+p9nFTRKHVq//WoEXPrd9d7YB7jXSIg/+Sn0/9C6VNtwvLlJ9alTzyCG1XiSDVvD1kcdnY+boQqF6VI="
        on:
          all_branches: true
    - name: "Publish to PyPi"
      if: tag IS present
      before_deploy:
        - sed -e "s/version = 0.0.0/version = $TRAVIS_VERSION/" -i "" setup.cfg
        - python3 -m build
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: sqXw37YezxzLsW5GjpNxOd3FDJYG7wDULXNiMj6nJCT6ZRhaOEDQsVjfnI0vAne+waOGc6aUdktnQeVRm4CYzo0Vm/UVYPdduXtGh5JcSD1wiZ0z0y6+5G5iH8Jf5NDPdniT3vsed4N8i799FHyo/qlrjfBx3vdpqsr21XTL7GcL13cGCaaPRvBT9nUIkzNognjD18gx/Mnwtg4lBXev5DRIPuxC6rjGRZxrYsiROY6x9Ufv3jJXQ24WZJTnNLH9742JB36IA/WUsoADrsCEmqj5hPx5nkx5sEusneaJtn+JHUaZ2ipbEtiPpAn6wsklprm418Z55yXoYWT2FEtkFCWtvLF6Y5ORkgaDZ4x0AQXj30Xef4Jrfjjc3YOx/yfUec2ABd3tAKo3sczi/gO4QHLyWi8ZrzKMhyahle5GeovJ5cCNxQFNj/9ubtgCvOgBYC2F2SiFMkkEbfrCRe7OoUP6LqMi6sj0Av4OrO78ljCG4sy7UUW1n3IT8zhYO305Kb4Ia3Oij2MPOrrV9Ho0xosKF17qWAmHQGUTIGFnGB0b+bwCnI00ZLBEA/L0RZrGHurvtvs2oMKmnr5CLw9o+YfvfJ0zZKWhRZde0nI50gf4bwcClBJSDVWU/cReFHuQA1ptnP8/HvnycBPtVV/VBiLbnQVVhtx/YrV8FPu+dIQ=
        on:
          tags: true
        skip_cleanup: true

