language: python
python:
  - 3.9
  - 3.8

branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+$

before_install:
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"
install:
  - pip3 install .
  - python3 -m pip install --upgrade build
before_script:
  - pip3 install pytest 
script:
  - pytest

stages:
  - name: test
    if: tag IS blank

jobs:
  include:
    - name: "Publish GitHub release"
      stage: deploy
      if: branch = main
      install:
        - pip3 install bump2version
        - python3 -m pip install --upgrade build
      before_script:
        - CURRENT_VERSION=$(git describe --tags --abbrev=0)
        - BUMP=patch
        - if (git log $CURRENT_VERSION..HEAD | grep -q "\[bump:minor\]"); then BUMP=minor; fi
        - if (git log $CURRENT_VERSION..HEAD | grep -q "\[bump:major\]"); then BUMP=major; fi
      script:
        - bump2version --current-version="$CURRENT_VERSION" $BUMP --tag --no-configured-files
      before_deploy: python3 -m build
      deploy:
        provider: releases
        api_key:
          secure: RalfF2YpboOqxCHNnywGGTkTN/Dkz9txg+cOXBFFW4flvKqjB6Wt0U6lbaCkCdPSeupjxq+MgqMepR9qp+EZNfIL49NXcN2WndpN94bLWeFR+Kiv5EPXo2otexSjsfBEfn7RuZgGQWm8a50oJ0wTk4AEiH00+5C4lyzcXXSvXHkl/egLGbpkhy2sV994nbuhYFyGafEVbDeOhqsqGDujO/qRRR/dPyLHT2rYFcEGqhP5B4y/bBpn3ujFeiqkDnDJ2jDm9ZFzMoumc8YqBQvJ+AjJopDWjyn1TjATMEmvq+E37XmbPC5EA3xvyRW043GFl1Iwaatrnhbf8G29kSUen2WcmdblczaZEX7d1ObOl9LT6X7jZEl7tgwb0cmd37aHqjjv70eyBghPbUSHknY8Gb4kNGQNz6IMTkCzTe4bI35r4kJG2Xc9SyDt9ITKhy7cbyW+shqYaSVvoVFWcZofVW6KwTqeaUYg6Ug2GHoOzJHtzEn6Rqk8FEgPYRwbjm9HBmCDqAEgJkqhMEqR7rsodmZ4Rfb7OKUTm4DqobQr6/+DS1kKgGyXQL5hkQOhyJ8rhieqpuOotn57lvzoy8ley2ZfddBhD/Mz6VHbb4YfwnDzOqfFxpIJw2TkfM38oigta9ysXn2T+F0bqnftNsMPl2/stZ0EX+NCdn9fxibYlBk=
        file: dist/*
        skip_cleanup: true
        on:
          all_branches: true

    - name: "Publish to PyPi"
      stage: deploy
      if: tag IS present
      script:
        - sed -e "s/version = 0.0.0/version = $TRAVIS_VERSION/" -i "" setup.cfg
      before_deploy: python3 -m build
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: VFwvkDmlq1rDwmKl6GxvWwnxVIyGGYe/hYqGqedOAAKGmI07WeM4oOSefHljuTXtCK2Lfu9RM1/bn1d1bRNROS1wD+sV5Jd2CqyrriCD/PBhL++B2BZvDOotxY3UTAz92UZ2n44dEGIAVFGd6MasA6vPYEEp5BMqUolrFJx0cf7UqZOpr3/YmTriq9wuinIlMuSmArwlPJHn4Th27vVZPHH6hw0VGy4KhUwnXwmEpEGg2r70uxo1GHf4pjUcRJayNAC0d80wSyQW6mFHEc5fE2qI6dbKk1HbZKeWLgjwAl8FzTu5+DGjtvkQoZGPNWc33scGra7zn5J2EgbcxVamam27eAcXjo3zqfAod7M8Ic21tzoB/MwsLCdaqTAWbLHTlF7Xn0pZnPrsEA/LpT9z5MizX4EHZHMvJv43vcALZ+FZd6lLuhYOkQeU6PC+S3ByvuDkOKzLLnp52LXOMbLLgQPt2d+goDPAV/MTMWM2+Ini0w6qogLXlL33osheeN92V8RJFPGKyJ012XNiil8gnpwBUm4KGXkf5Ci/HAaGvUUHLBfGVlQeHx6KG3D+zi08zsoiFhYbrh9cFTaHNXMWXVN1amplmTBFr6RfhV8tnrh7cxAkYhrIfLMJ4VRUKmpoWIg5tKsiIff9vBGdtKWT5VmU3XkQk4VMsCWxK1AxZkI=
        on:
          tags: true
        skip_cleanup: true

