language: python
dist: jammy

python:
  - 3.10
  - 3.9
  - 3.8

branches:
  only:
    - main
    - travis
    - /^v\d+\.\d+\.\d+$/

before_install:
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"
  
install:
  - '[[ ! "$TRAVIS_PYTHON_VERSION" =~ "3.9" ]] || source ~/virtualenv/python3.9/bin/activate'
  - pip3 install .
  
before_script:
  - pip3 install pytest 

script:
  - pytest

stages:
  - name: test
    if: tag IS blank

jobs:
  include:
    - name: "Publish GitHub release"
      stage: deploy
      if: branch = main AND type = push
      install:
        - pip3 install bump2version
      before_script:
        - CURRENT_VERSION=$(git describe --tags --abbrev=0)
        - BUMP=patch
        - if (git log $CURRENT_VERSION..HEAD | grep -q -i "\[bump:minor\]"); then BUMP=minor; fi
        - if (git log $CURRENT_VERSION..HEAD | grep -q -i "\[bump:major\]"); then BUMP=major; fi
      script:
        - bump2version --current-version="$CURRENT_VERSION" $BUMP --tag --no-configured-files
      deploy:
        provider: releases
        api_key:
          secure: RalfF2YpboOqxCHNnywGGTkTN/Dkz9txg+cOXBFFW4flvKqjB6Wt0U6lbaCkCdPSeupjxq+MgqMepR9qp+EZNfIL49NXcN2WndpN94bLWeFR+Kiv5EPXo2otexSjsfBEfn7RuZgGQWm8a50oJ0wTk4AEiH00+5C4lyzcXXSvXHkl/egLGbpkhy2sV994nbuhYFyGafEVbDeOhqsqGDujO/qRRR/dPyLHT2rYFcEGqhP5B4y/bBpn3ujFeiqkDnDJ2jDm9ZFzMoumc8YqBQvJ+AjJopDWjyn1TjATMEmvq+E37XmbPC5EA3xvyRW043GFl1Iwaatrnhbf8G29kSUen2WcmdblczaZEX7d1ObOl9LT6X7jZEl7tgwb0cmd37aHqjjv70eyBghPbUSHknY8Gb4kNGQNz6IMTkCzTe4bI35r4kJG2Xc9SyDt9ITKhy7cbyW+shqYaSVvoVFWcZofVW6KwTqeaUYg6Ug2GHoOzJHtzEn6Rqk8FEgPYRwbjm9HBmCDqAEgJkqhMEqR7rsodmZ4Rfb7OKUTm4DqobQr6/+DS1kKgGyXQL5hkQOhyJ8rhieqpuOotn57lvzoy8ley2ZfddBhD/Mz6VHbb4YfwnDzOqfFxpIJw2TkfM38oigta9ysXn2T+F0bqnftNsMPl2/stZ0EX+NCdn9fxibYlBk=
        skip_cleanup: true
        on:
          all_branches: true

    - name: "Publish to PyPi"
      stage: deploy
      if: tag IS present
      before_install:
        - sed -e "s/version = 0.0.0/version = $TRAVIS_TAG/" -i setup.cfg
      before_script:
        - pip3 install --upgrade build
      script:
        - python3 -m build
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: "ZZ6AjFXbrbp05sE1Sxgt+D2F3UVm6ZVpk8trv2H7u+VBNnTeim6aLwyfWPe7Op8NMZOBhmCW/zFGqW9KD26uWAM+tkXLrm7wmTTsucj5DC2m9yp3qzI16sK2UxHWvHD6Bs9BWMWXHnm5uuVDH0HcXTK2CSkHUaDI/KTDNMBYQsmW1tqykYKivQX3veib4ANX+8y8FYz2l8ka092FFiG/PpULdbTF8sFXW/GBvKlf3bHkh2nVZmZjS1jThlOowO0OmNnzspceWyo6ula3Zj+lIMwdc4xfaAzPzLsXn3ENBcXhxSkQqrlvN9FZ8LqUkubUHthUo45Qk14wunGAZ5pxdtyiYrLxD0ZofAfeEdDDo4Opnc/rfbILIT2zMHuBUDCR9wW4dTu6ohHOmg1KhNAwvHskwxLG2Rll/eQTLasfZfIgjAyGtxotpn7ybCftnSYC69eOWumDbq3jJ0/PtZvmC2oYfpxq5xlryBS0Edwunt2c76LSrZuz2ihOBlx7YpRDRmmwM0pFVORiE4thnCmRGhUL23WJzE8cD+qd8Q3JebiWsPEqM2QSMP3BvUrV1vVQYTcY/zJ3wdyLdUZXuD5rAjw29eHwzZFIPiQzeRIeU9GOG5jf/E1GFukWoO85Sj1juuLFJLNcfAsl9Mon9vX4EAH0CKPxEEvBlTtlDOX8gYM="
        on:
          tags: true
        skip_cleanup: true

