language: python
branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+$

before_install:
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"
install:
  - pip3 install .
  - pip3 install pytest 

jobs:
  include:
    - name: "Run tests and create new version"
      if: branch = main
      python:
        - '3.8'
        - '3.9'
      script:
        - python3 -m pytest
      before_deploy:
        - CURRENT_VERSION=$(git describe --tags --abbrev=0)
        - BUMP=patch
        - if (git log $CURRENT_VERSION..HEAD | grep -q "\[bump:minor\]"); then BUMP=minor; fi
        - if (git log $CURRENT_VERSION..HEAD | grep -q "\[bump:major\]"); then BUMP=major; fi
        - pip3 install bump2version        
        - bump2version --curent-version="$CURRENT_VERSION" $BUMP --tag --no-configured-files
      deploy:
        provider: releases
        api_key:
          secure: "uDGf5E0/hq8yrxdtW1XLzP9njpnEtd/7k/z7End6+JLPfZFnn7xgDiEzjK9+75ju3DA8BpD8hVxUdD+jG8VpYzvZC1SafChIrxMwgUVHKODfyi7UetVyS4tZR5SxybX0CSRtiprLJVgD1X0DQhK3xCIo9Y8bTB9ibPnKvgDJ8b6Ra/eISS/uMVq4j3cG1/p+3CirqsV7VW5z36aCJTQkYehrIsAXbjGjvmvKjQvJfcw6IgCKkHsNhwyhRIrMAD2MAtn/mnQu3ZQX2cgkPBhecABhvqcXTj0g5snNR+LdOseF93iY7cXDVEr5DxVzUZvLAX6gqFwZ9p7EYvvic8q0vX7m83H1uFRKsD+4ckcf4GphYT+XQFe7sRJdCT6iKfOxb58vl1KcYNSERThsaUP5k0yrz+WgTDYzM6hOvyUSpigOVw59vmEHlMbpQe4J/7R0e1tGF0y0yxQy+NWtICEzIvkgEFwXlgNf9K4C4h4YvjkyxOEZ2Tx2wfXAAA+k/oRPAEFd9Hrwpca0pjEv9qrLNif3roNCvYSNxY4sqBqVHe6hKKzvxLHz9D9RpXKvA6hNu2upP15abTven8fYZJkQ7DhWjdJa1NnshKlI3szHbpSYRKoVJzrYikMHLSFLiASJqyHbO8sSPCJwYTL2cDlFBvcl6pNT8viZU49fqBby5Tk="
        on:
          all_branches: true        
    - name: "Publish to PyPi"
      if: tag IS present
      before_deploy:
        - sed -e "s/version = 0.0.0/version = $TRAVIS_VERSION/" -i "" setup.cfg
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: Ga+rje+j3zf9Rvm3qglgpJycew9rU38ROytMjciqVTD+n2oqpaQRWTCtAmvooE5+hFHXJDV1MW9rTijaBXucCvj12YLz4YqU5arU/NLvKPhJTZx8eaIUjWf8VMcZrYmENVyea9LE0zW9gKGmKLX720bAhMM4WOnel6a69Lo4WiNDbZyKd9J99rZbMc2Nyi1Bxx2XN1YX3Qsme4OR5C3a1rDZNOs8jSCFc7Nuwfes1hk0MSP3VMVHbCUwJLdoMI0Bp8YoRmyhAXGaH5Qz1YxTdZa3/zXRVSL9wruxGH3/o+bmeVR+cPLIxtQhIKgbMDMCf2g782jjKF7EWZ7727R/HOWxpHks0DaXTBgvGL515MsK3CcAbBUFLF/RjoYJ/8lVodE2jRzJ5gGivghn8rGuwcOB6PoNV1edDmlrP3aOWIwur5uK1atAH41qGBLJKZr7EhLXX39MuK52kjwWFl14onisRFbM7R3DEtPRYvskH5vpWJIrQ1wAGkGQeh+eophplTfCGa3fiZfpod05XD4rUgtimXVSlwRLw5dWoJCpo0XcI6lcaf61glofbV291y0Uhbtt1LN6f9dB5VCoSHv+qTKZ8306YMtkUdm8rZ06ldB2PaG5Lum44Y9qAjXL3d3Z0pPRrw8Kye+llXnjfOM90B5heNZz3HPbJHxlixeqzBw=
        distributions: sdist bdist_wheel
        cleanup: true
        on:
          tags: true
